# Generated by Django 4.0 on 2021-12-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='video',
            field=models.FileField(null=True, upload_to='video/%y'),
        ),
    ]
