# Generated by Django 4.0 on 2021-12-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='video',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
