# Generated by Django 4.0 on 2021-12-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='video',
        ),
    ]
